apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: poc
build:
  artifacts:
    - image: target-server
      jib:
        project: target-server
    - image: nginx1
      context: nginx1
      docker:
        dockerfile: Dockerfile
    - image: nginx2
      context: nginx2
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/target-server.yaml
      - k8s/nginx1.yaml
      - k8s/nginx2.yaml
      - k8s/http-client.yaml
